name: app_jenosize
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  dio: ^4.0.6
  flutter_vector_icons: ^1.0.0
  flutter_easyloading: ^3.0.0
  flutter_form_builder: ^6.2.0
  textless: ^6.6.6
  logger: ^1.1.0
  freezed: ^2.3.2
  flutter_dotenv: ^5.0.2  
  shimmer_animation: ^2.1.0+1
  cached_network_image: ^3.1.0+1




dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

  build_runner: ^2.1.2
  json_serializable: any
  hive_generator: any

flutter: 
  uses-material-design: true

  assets:
    - .env
    - assets/images/

get_cli:
  sub_folder: false
